name: Create Release

on:
  push:
    tags:
      - 'v*' # Triggers the workflow only when a tag starting with 'v' is pushed

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release and upload assets

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # - name: Generate GitHub App Token
      #   id: app-token
      #   uses: actions/create-github-app-token@v1
      #   with:
      #     app-id: ${{ secrets.APP_ID }}
      #     private-key: ${{ secrets.APP_PRIVATE_KEY }}
      #     owner: ${{ github.repository_owner }}

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true # Automatically generates release notes based on commit history
        # env:
        #   GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
